# Use Node.js LTS version as base image
FROM node:22

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .


# Start development server
CMD ["npm", "run", "dev"]
